<?php

namespace FINNPartners\Theme\Block\Instance;

use FINNPartners\Theme\Block\Instance\Fields\CarouselFields;
use WpAdvanceCustomFieldsExtend\AbstractClass\Block;

class Carousel extends Block
{

    /**
     * @var CarouselFields
     */
    private $fields;

    /**
     * @param int|false $postId
     * @param array $block
     * @param bool $isPreview
     * @return void
     */
    public function __construct($postId = false, array $block = [], bool $isPreview = false)
    {
        $this->setFields(new CarouselFields($postId, !empty($block['id']) ? $block['id'] : false));

        parent::__construct($block);

        $this->setIsPreview($isPreview)->execute();
    }

    public function previewNotAvailableHTML(): void
    {
        if (empty($this->getFields()->getCarousel())) {
            parent::previewNotAvailableHTML(); // TODO: Change the autogenerated stub
        }
    }

    /**
     * @return CarouselFields
     */
    public function getFields(): CarouselFields
    {
        return $this->fields;
    }

    /**
     * @param CarouselFields $fields
     * @return $this
     */
    protected function setFields(CarouselFields $fields): self
    {
        $this->fields = $fields;

        return $this;
    }
}