<?php
namespace FINNPartners\Theme\Block\Instance;

use FINNPartners\Theme\Block\Instance\Fields\FrameFields;
use FINNPartners\Theme\Theme;
use WpAdvanceCustomFieldsExtend\AbstractClass\Block;
use WpAdvanceCustomFieldsExtend\Service\Media;

class Frame extends Block {

    /**
     * @var FrameFields 
     */
    private $fields;
    
    /**
     * @param int|false $postId
     * @param array $block
     * @param bool $isPreview
     * @return void
     */
    public function __construct($postId = false, array $block = [], bool $isPreview = false)
    {        
        $this->setFields(new FrameFields($postId, !empty($block['id']) ? $block['id'] : false));
        
        parent::__construct($block);
        
        $this->setIsPreview($isPreview)->execute();
    }

    public function execute(): Block
    {
        $this->setBackgroundColor($this->getFields()->getBackgroundColor());

        if(($this->getFields()->getBackgroundImage() instanceof Media)) {
            $this->addCSSClass('has-img-background-color');
            $this->getFields()->getBackgroundImage()->setCrop(Theme::IMAGE_SIZES['frame']['name']);
        }

        if($this->getFields()->isClearBackgroundOnMobile()) {
            $this->addCSSClass('clear-background-on-mobile');
        }
        
        return parent::execute(); // TODO: Change the autogenerated stub
    }

    /**
     * @return FrameFields
     */
    public function getFields(): FrameFields
    {
        return $this->fields;
    }
    
    /**
     * @param FrameFields $fields
     * @return $this
     */
    protected function setFields(FrameFields $fields): self
    {
        $this->fields = $fields;
        
        return $this;
    }
}