<?php

namespace FINNPartners\Theme\Block\Instance;

use FINNPartners\Theme\Block\Instance\Fields\PartnersFeaturedFields;
use FINNPartners\Theme\PostType\Instance\Partner;
use FINNPartners\Theme\PostType\Register\Partner as PartnerPostType;
use FINNPartners\Theme\Theme;
use WP_Query;
use WpAdvanceCustomFieldsExtend\AbstractClass\Block;
use WpAdvanceCustomFieldsExtend\Service\Media;
use WpAdvanceCustomFieldsExtend\Service\Post2PostHelper;
use WpAdvanceCustomFieldsExtend\Service\QueryHelper;

class PartnersFeatured extends Block
{

    /**
     * @var PartnersFeaturedFields
     */
    private $fields;

    /**
     * @var Partner[]|false
     */
    private $partners = null;

    /**
     * @var bool
     */
    private $sideImg = false;

    /**
     * @param int|false $postId
     * @param array $block
     * @param bool $isPreview
     * @return void
     */
    public function __construct($postId = false, array $block = [], bool $isPreview = false)
    {
        $this->setFields(new PartnersFeaturedFields($postId, !empty($block['id']) ? $block['id'] : false));

        parent::__construct($block);

        $this->setIsPreview($isPreview)->execute();
    }

    public function execute(): Block
    {
        $this->setSideImg(in_array('is-style-side-img', !empty($this->getCSSClasses()) ? $this->getCSSClasses() : []));

        if ($this->getFields()->isAddCta() && !$this->getFields()->getLinkCta()) {
            $this->getFields()->setLinkCta($this->getFields()->getPartnersLanding());
        }

        return parent::execute(); // TODO: Change the autogenerated stub
    }

    /**
     * @return PartnersFeaturedFields
     */
    public function getFields(): PartnersFeaturedFields
    {
        return $this->fields;
    }

    /**
     * @param PartnersFeaturedFields $fields
     * @return $this
     */
    protected function setFields(PartnersFeaturedFields $fields): self
    {
        $this->fields = $fields;

        return $this;
    }

    public function previewNotAvailableHTML(): void
    {
        if ($this->isPreview() && !$this->getPartners()) {
            parent::previewNotAvailableHTML(); // TODO: Change the autogenerated stub
        }
    }

    /**
     * @return false|Partner[]|null
     */
    public function getPartners()
    {
        if (is_null($this->partners)) {
            $partners = false;

            if ($this->getFields()->getDataSource()) {
                $queryHelper = new QueryHelper();
                $isQuery = false;

                switch ($this->getFields()->getDataSource()) {
                    case PartnersFeaturedFields::DATASOURCE_MANUAL_SELECTION_VALUE:
                        $isQuery = !empty($this->getFields()->getPartners());

                        if ($isQuery) {
                            $queryHelper->setArgs([
                                'post_type' => [PartnerPostType::POST_TYPE],
                                'post_status' => ['publish'],
                                'posts_per_page' => count($this->getFields()->getPartners()),
                                'fields' => 'ids',
                                'post__in' => $this->getFields()->getPartners(),
                                'orderby' => ['post__in' => 'asc'],
                            ]);
                        }
                        break;
                    default:
                        $isQuery = true;
                        $queryHelper->setArgs([
                            'post_type' => [PartnerPostType::POST_TYPE],
                            'post_status' => ['publish'],
                            'post__not_in' => [$this->getFields()->getPostId()],
                            'posts_per_page' => $this->getFields()->getLimit(),
                            'fields' => 'ids',
                        ]);
                        break;
                }

                if ($isQuery) {
                    $partners = new WP_Query($queryHelper->getArgs());
                    $partners = $partners->have_posts() ? $partners->get_posts() : false;

                    if ($partners) {
                        foreach ($partners as &$partner) {
                            /** @var int $partner */
                            $partner = new Partner($partner);
                            /** @var Partner $partner */

                            if (($partner->getFields()->getThumbnail() instanceof Media)) {
                                $partner->getFields()->getThumbnail()->setCrop(Theme::IMAGE_SIZES['highlighted_resources_list']['name']);
                            }
                        }
                    }
                }
            }

            $this->setPartners($partners);
        }

        return $this->partners;
    }

    /**
     * @param false|Partner[]|null $partners
     * @return PartnersFeatured
     */
    public function setPartners($partners)
    {
        $this->partners = $partners;
        return $this;
    }

    /**
     * @return bool
     */
    public function isSideImg(): bool
    {
        return $this->sideImg;
    }

    /**
     * @param bool $sideImg
     * @return PartnersFeatured
     */
    public function setSideImg(bool $sideImg): PartnersFeatured
    {
        $this->sideImg = $sideImg;
        return $this;
    }
}