<?php

namespace FINNPartners\Theme\Block\Instance;

use FINNPartners\Theme\Block\Instance\Fields\ResourcesListFields;
use FINNPartners\Theme\PostType\Instance\Resource;
use FINNPartners\Theme\PostType\Register\Resource as PostTypeResource;
use FINNPartners\Theme\PostType\Register\Topic as TopicRegister;
use FINNPartners\Theme\Taxonomy\Keyword;
use FINNPartners\Theme\Taxonomy\Type;
use FINNPartners\Theme\Theme;
use WP_Query;
use WpAdvanceCustomFieldsExtend\AbstractClass\Block;
use WpAdvanceCustomFieldsExtend\Service\Media;
use WpAdvanceCustomFieldsExtend\Service\Post2PostHelper;
use WpAdvanceCustomFieldsExtend\Service\QueryHelper;

class ResourcesList extends Block
{

    /**
     * @var ResourcesListFields
     */
    private $fields;

    /**
     * @var Resource[]|false
     */
    private $resources = null;

    /**
     * @param int|false $postId
     * @param array $block
     * @param bool $isPreview
     * @return void
     */
    public function __construct($postId = false, array $block = [], bool $isPreview = false)
    {
        $this->setFields(new ResourcesListFields($postId, !empty($block['id']) ? $block['id'] : false));

        parent::__construct($block);

        $this->setIsPreview($isPreview)->execute();
    }

    public function execute(): Block
    {
        return parent::execute(); // TODO: Change the autogenerated stub
    }

    public function previewNotAvailableHTML(): void
    {
        if (!$this->getResources() && $this->isPreview()) {
            parent::previewNotAvailableHTML(); // TODO: Change the autogenerated stub
        }
    }

    /**
     * @return false|Resource[]
     */
    public function getResources()
    {
        if (is_null($this->resources)) {
            $resources = false;

            if ($this->getFields()->getDataSource()) {
                $queryHelper = new QueryHelper();
                $isQuery = false;

                switch ($this->getFields()->getDataSource()) {
                    case ResourcesListFields::DATASOURCE_MANUAL_VALUE:
                        $isQuery = !empty($this->getFields()->getResources());

                        if ($isQuery) {
                            $queryHelper->setArgs([
                                'post_type' => [PostTypeResource::POST_TYPE],
                                'post_status' => ['publish'],
                                'posts_per_page' => count($this->getFields()->getResources()),
                                'fields' => 'ids',
                                'post__in' => $this->getFields()->getResources(),
                                'orderby' => ['post__in' => 'asc'],
                            ]);
                        }
                        break;
                    case ResourcesListFields::DATASOURCE_CONNECT_TO_CURRENT_POST_VALUE:
                        $currentPostType = get_post_type($this->getFields()->getPostId());
                        $topicIds = false;

                        if ($currentPostType === PostTypeResource::POST_TYPE) {
                            $currentPostType = TopicRegister::POST_TYPE;
                            /** @var Resource $ResourcePostTypeInstance */
                            $ResourcePostTypeInstance = new Resource(get_the_ID());

                            if (!empty($ResourcePostTypeInstance->getFields()->getTopics())) {
                                $topicIds = [];
                                foreach ($ResourcePostTypeInstance->getFields()->getTopics() as $topic) {
                                    /** @var Topic $topic */
                                    $topicIds[] = $topic->getFields()->getPostId();
                                }
                            }
                        }

                        /** @var Post2PostHelper $Post2PostHelper */
                        $Post2PostHelper = Post2PostHelper::getInstances(PostTypeResource::POST_TYPE, $currentPostType);
                        $posts = $Post2PostHelper ? $Post2PostHelper->getPostsLinked(!empty($topicIds) ? $topicIds : $this->getFields()->getPostId()) : false;

                        $isQuery = !empty($posts);

                        if ($isQuery) {
                            $queryHelper->setArgs([
                                'post_type' => [PostTypeResource::POST_TYPE],
                                'post_status' => ['publish'],
                                'post__not_in' => [$this->getFields()->getPostId()],
                                'post__in' => $posts,
                                'posts_per_page' => $this->getFields()->getLimit(),
                                'fields' => 'ids',
                                'orderby' => ['post__in' => 'asc'],
                            ]);
                        }
                        break;
                    default:
                        $isQuery = true;

                        $queryHelper->setArgs([
                            'post_type' => [PostTypeResource::POST_TYPE],
                            'post__not_in' => [$this->getFields()->getPostId()],
                            'post_status' => ['publish'],
                            'posts_per_page' => $this->getFields()->getLimit(),
                            'fields' => 'ids',
                        ]);

                        if (!empty($this->getFields()->getKeywordsTaxonomy())) {
                            $queryHelper->addTaxQuery(Keyword::TAXONOMY_NAME, $this->getFields()->getKeywordsTaxonomy());
                        }

                        if (!empty($this->getFields()->getTypesTaxonomy())) {
                            $queryHelper->addTaxQuery(Type::TAXONOMY_NAME, $this->getFields()->getTypesTaxonomy());
                        }
                        break;
                }

                if ($isQuery) {
                    $resources = new WP_Query($queryHelper->getArgs());
                    $resources = $resources->have_posts() ? $resources->get_posts() : false;

                    if ($resources) {
                        foreach ($resources as &$resource) {
                            /** @var int $resource */
                            $resource = new Resource($resource);
                            /** @var Resource $resource */

                            if (($resource->getFields()->getThumbnail() instanceof Media)) {
                                $resource->getFields()->getThumbnail()->setCrop(Theme::IMAGE_SIZES['highlighted_resources_list']['name']);
                            }
                        }
                    }
                }
            }

            $this->setResources($resources);
        }

        return $this->resources;
    }

    /**
     * @param false|Resource[] $resources
     * @return ResourcesList
     */
    public function setResources($resources)
    {
        $this->resources = $resources;
        return $this;
    }

    /**
     * @return ResourcesListFields
     */
    public function getFields(): ResourcesListFields
    {
        return $this->fields;
    }

    /**
     * @param ResourcesListFields $fields
     * @return $this
     */
    protected function setFields(ResourcesListFields $fields): self
    {
        $this->fields = $fields;

        return $this;
    }
}