<?php
namespace FINNPartners\Theme\Block\Instance;

use FINNPartners\Theme\Block\Instance\Fields\TopicFields;
use FINNPartners\Theme\Theme;
use WpAdvanceCustomFieldsExtend\AbstractClass\Block;
use WpAdvanceCustomFieldsExtend\Service\Media;

class Topic extends Block {

    /**
     * @var TopicFields 
     */
    private $fields;
    
    /**
     * @param int|false $postId
     * @param array $block
     * @param bool $isPreview
     * @return void
     */
    public function __construct($postId = false, array $block = [], bool $isPreview = false)
    {        
        $this->setFields(new TopicFields($postId, !empty($block['id']) ? $block['id'] : false));
        
        parent::__construct($block);
        
        $this->setIsPreview($isPreview)->execute();
    }

    public function execute(): Block
    {
        if(($this->getFields()->getImage() instanceof Media)) {
            $this->getFields()->getImage()->setCrop(Theme::IMAGE_SIZES['topic']['name']);
        }
        return parent::execute(); // TODO: Change the autogenerated stub
    }

    /**
     * @return TopicFields
     */
    public function getFields(): TopicFields
    {
        return $this->fields;
    }
    
    /**
     * @param TopicFields $fields
     * @return $this
     */
    protected function setFields(TopicFields $fields): self
    {
        $this->fields = $fields;
        
        return $this;
    }
}