<?php
/**
 * Functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package WordPress
 * @subpackage FinnPartners
 * @since FinnPartners 1.0
 */

namespace FINNPartners\Theme\Service;

use WpAdvanceCustomFieldsExtend\Service\AbstractClass\CacheHelper;

class ThemeCacheHelper extends CacheHelper
{
    /**
     * @Navs
     */

    /**
     * @Others
     */

    /**
     * @param $class
     * @return CacheHelper
     */
    public static function getHelper($class = self::class)
    {
        return parent::getHelper($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        /**
         * @Navs
         */
        $this->registerCacheClearEvent(self::CLEAR_CACHE_MENU_UPDATE, self::APP_NAVIGATION);

        /**
         * @PostType
         */
        $this->registerCacheClearEvent(self::CLEAR_CACHE_POST_INSERT, self::APP_POST);
        $this->registerCacheClearEvent(self::CLEAR_CACHE_POST_UPDATE, self::APP_POST);
        $this->registerCacheClearEvent(self::CLEAR_CACHE_POST_DELETE, self::APP_POST);

        /**
         * @Taxonomy
         */
        $this->registerCacheClearEvent(self::CLEAR_CACHE_TERMS_CREATE, self::APP_POST);
        $this->registerCacheClearEvent(self::CLEAR_CACHE_TERMS_EDIT, self::APP_POST);
        $this->registerCacheClearEvent(self::CLEAR_CACHE_TERMS_DELETE, self::APP_POST);

        parent::__construct();
    }
}

