<?php

namespace FINNPartners\Theme\PostType\Register;

use FINNPartners\Theme\Taxonomy\Keyword;
use FINNPartners\Theme\Theme;
use WpAdvanceCustomFieldsExtend\AbstractClass\RegisterPostType;

class BlogPost extends RegisterPostType
{
    const POST_TYPE = 'post';

    const SINGULAR_NAME = 'Blog Post';
    const PLURAL_NAME = 'Blog Posts';

    const TAXONOMIES = [
    ];



    /**
     * @param string $postType
     * @param string $class
     * @return BlogPost
     */
    public static function getInstance(string $postType = self::POST_TYPE, string $class = BlogPost::class): BlogPost
    {
        return parent::getInstance($postType, $class); // TODO: Change the autogenerated stub
    }
}