<?php

namespace FINNPartners\Theme\PostType\Register;

use FINNPartners\Theme\Taxonomy\PartnerType;
use FINNPartners\Theme\Taxonomy\Region;
use FINNPartners\Theme\Theme;
use stdClass;
use WpAdvanceCustomFieldsExtend\AbstractClass\RegisterPostType;

class Partner extends RegisterPostType
{
    const POST_TYPE = 'partner';

    const SINGULAR_NAME = 'Partner';
    const PLURAL_NAME = 'Partners';

    const ICON = 'dashicons-groups';

    const TAXONOMIES = [
        Region::TAXONOMY_NAME,
        PartnerType::TAXONOMY_NAME,
    ];

    public function __construct(string $postType)
    {
        parent::__construct($postType);

        $labels = new stdClass;
        $labels->name = self::PLURAL_NAME;
        $labels->singular_name = self::SINGULAR_NAME;
        $labels->add_new_item = __("Add New " . self::SINGULAR_NAME, Theme::DOMAIN);
        $labels->new_item_name = __("New " . self::SINGULAR_NAME, Theme::DOMAIN);
        $labels->edit_item = __("Edit " . self::SINGULAR_NAME, Theme::DOMAIN);
        $labels->update_item = __("Update " . self::SINGULAR_NAME, Theme::DOMAIN);
        $labels->search_items = __("Search " . self::SINGULAR_NAME, Theme::DOMAIN);
        $labels->popular_items = __("Popular " . self::PLURAL_NAME, Theme::DOMAIN);
        $labels->all_items = __("All " . self::PLURAL_NAME, Theme::DOMAIN);
        $labels->add_or_remove_items = __("Add or remove " . self::PLURAL_NAME, Theme::DOMAIN);
        $labels->separate_items_with_commas = __("Separate " . self::PLURAL_NAME . " with commas", Theme::DOMAIN);
        $labels->choose_from_most_used = __("All " . self::PLURAL_NAME, Theme::DOMAIN);
        $labels->front = self::PLURAL_NAME;
        $labels->detail = self::SINGULAR_NAME;
        $labels->detail_plural = self::PLURAL_NAME;

        $this->setLabel(self::PLURAL_NAME)
            ->setLabels($labels)
            ->setPublic(true)
            ->setHasArchive(false)
            ->setSupports(['title', 'thumbnail', 'editor', 'excerpt', 'revisions', 'page-attributes'])
            ->setQueryVar(true)
            ->setMenuIcon(self::ICON)
            ->setHierarchical(true)
            ->setShowInRest(true)
            ->setRestBase(self::POST_TYPE)
            ->register();


	    add_filter( 'post_type_link', [$this, 'updatePermalink'], 10, 3 );

    }

	public function updatePermalink( $url, $post, $leavename=false ) {
	    if ( $post->post_type == $this::POST_TYPE ) {
			if(get_field('skip_details_page', $post->ID) && get_field('website', $post->ID)){
				$url = get_field('website', $post->ID);
			}
	    }
		return $url;
	}


/**
     * @param string $postType
     * @param string $class
     * @return Partner
     */
    public static function getInstance(string $postType = self::POST_TYPE, string $class = Partner::class): Partner
    {
        return parent::getInstance($postType, $class); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function p2pInit(): void
    {
    }
}
