<?php
/**
 * Functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package WordPress
 * @subpackage FinnPartners
 * @since FinnPartners 1.0
 */

namespace FINNPartners\Theme\BlockCategory;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlockCategory;

class CustomBlocks extends CustomBlockCategory
{
    const SLUG = 'fp-custom-blocks';
    const TITLE = 'Get Network Visibility - Blocks';

    /**
     * @param string $class
     * @return CustomBlocks
     */
    public static function getInstance(string $class = CustomBlocks::class): CustomBlocks
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setTitle(self::TITLE)
            ->setSlug(self::SLUG)
            ->setDefault(true);

        parent::__construct();
    }
}
