<?php

namespace FINNPartners\Theme\Block\Register;


use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class AccordionContent extends CustomBlock
{
    const NAME = 'accordion-content';
    const FILENAME = 'accordion-content';
    const TITLE = 'Accordion Content';

    /**
     * @param string $class
     * @return AccordionContent
     */
    public static function getInstance(string $class = AccordionContent::class): AccordionContent
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setSupports(['jsx' => true, 'align' => false])
            ->setParent(['acf/' . Accordion::NAME])
            ;

        parent::__construct();
    }
}