<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class Accordion extends CustomBlock
{
    const NAME = 'accordion';
    const FILENAME = 'accordion';
    const TITLE = 'Accordion';

    /**
     * @param string $class
     * @return Accordion
     */
    public static function getInstance(string $class = Accordion::class): Accordion
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon('superhero')
            ->setSupports(['jsx' => true, 'align' => false]);

        parent::__construct();
    }
}