<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class ContentWithImage extends CustomBlock
{
    const NAME = 'content-with-image';
    const FILENAME = 'content-with-image';
    const TITLE = 'Content with image';

    const ICON = 'id';

    /**
     * @param string $class
     * @return ContentWithImage
     */
    public static function getInstance(string $class = ContentWithImage::class): ContentWithImage
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => ['left', 'right']]);

        parent::__construct();
    }
}