<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class ContentWithCallout extends CustomBlock
{
    const NAME = 'content-with-callout';
    const FILENAME = 'content-with-callout';
    const TITLE = 'Content with callout';

    const ICON = 'id';

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false])
            ->setAllowedBlocks(['core/paragraph', 'core/heading']);

        parent::__construct();
    }

    /**
     * @param string $class
     * @return ContentWithCallout
     */
    public static function getInstance(string $class = ContentWithCallout::class): ContentWithCallout
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }
}