<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;
use FINNPartners\Theme\Theme;

class EventsArchive extends CustomBlock
{
    const NAME = 'events-archive';
    const FILENAME = self::NAME;
    const TITLE = 'Events Archive';

    /**
     * @param string $class
     * @return EventsArchive
     */
    public static function getInstance(string $class = EventsArchive::class): EventsArchive
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords([Theme::DOMAIN])
            ->setIcon('superhero')
            ->setSupports(['anchor' => true, 'jsx' => false, 'align' => false])
        ;

        parent::__construct();
    }
}
