<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class FindTheResources extends CustomBlock
{
    const NAME = 'find-the-resources';
    const FILENAME = 'find-the-resources';
    const TITLE = 'Find The Resources';

    const ICON = 'id';

    /**
     * @param string $class
     * @return FindTheResources
     */
    public static function getInstance(string $class = FindTheResources::class): FindTheResources
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => false, 'align' => false]);

        parent::__construct();
    }
}