<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class Hero extends CustomBlock
{
    const NAME = 'hero';
    const FILENAME = 'hero';
    const TITLE = 'Hero';

    const ICON = 'id';
    /**
     * @param string $class
     * @return Hero
     */
    public static function getInstance(string $class = Hero::class): Hero
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false])
            ->setStyles([
                ['label' => 'Simple', 'name' => 'sample'],
                ['label' => 'Contact', 'name' => 'contact'],
            ]);

        $this->addFilter();
        parent::__construct();
    }

    public function addFilter() {
        add_filter('acf/load_field/name=ninja_forms', function ($field) {
            $forms = Ninja_Forms()->form()->get_forms();

            foreach ($forms as $form) {
                $field['choices'][$form->get_id()] = $form->get_setting('title');
            }

            return $field;
        }, 10);
    }
}