<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class HighlightedResourcesList extends CustomBlock
{
    const NAME = 'highlighted-resources-list';
    const FILENAME = 'highlighted-resources-list';
    const TITLE = 'Highlighted Resources List';

    const ICON = 'id';

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false]);

        parent::__construct();
    }

    /**
     * @param string $class
     * @return HighlightedResourcesList
     */
    public static function getInstance(string $class = HighlightedResourcesList::class): HighlightedResourcesList
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }
}