<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class MoreSolutionIndustry extends CustomBlock
{
    const NAME = 'more-solution-industry';
    const FILENAME = 'more-solution-industry';
    const TITLE = 'More Solution/Industry';

    const ICON = 'id';

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false]);

        parent::__construct();
    }

    /**
     * @param string $class
     * @return MoreSolutionIndustry
     */
    public static function getInstance(string $class = MoreSolutionIndustry::class): MoreSolutionIndustry
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }
}