<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\BlockStyle;

class Paragraph extends BlockStyle
{
    const STYLE_LARGE_TXT_LABEL = 'Large Text';
    const STYLE_LARGE_TXT = 'large-txt';

    const STYLE_NARROW_LABEL = 'Narrow';
    const STYLE_NARROW = 'narrow';

    /**
     * @param string $class
     * @return Paragraph
     */
    public static function getInstance(string $class = Paragraph::class): Paragraph
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function __construct()
    {
        $this->setBlockName('core/paragraph');
        $this->setName(self::STYLE_LARGE_TXT)->setLabel(self::STYLE_LARGE_TXT_LABEL)->registerBlockStyle();
        $this->setName(self::STYLE_NARROW)->setLabel(self::STYLE_NARROW_LABEL)->registerBlockStyle();

        parent::__construct();
    }
}