<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class PartnersFeatured extends CustomBlock
{
    const NAME = 'partners-featured';
    const FILENAME = 'partners-featured';
    const TITLE = 'Partners Featured';

    const ICON = 'id';

    /**
     * @param string $class
     * @return PartnersFeatured
     */
    public static function getInstance(string $class = PartnersFeatured::class): PartnersFeatured
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true])
            ->setStyles([
                ['label' => 'Side image', 'name' => 'side-img', 'isDefault' => false],
            ]);

        parent::__construct();
    }
}