<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class ReadMore extends CustomBlock
{
    const NAME = 'read-more';
    const FILENAME = 'read-more';
    const TITLE = 'Read More';

    const ICON = 'id';

    /**
     * @param string $class
     * @return ReadMore
     */
    public static function getInstance(string $class = ReadMore::class): ReadMore
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => ['center']]);

        parent::__construct();
    }
}