<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class Transcript extends CustomBlock
{
    const NAME = 'transcript';
    const FILENAME = 'transcript';
    const TITLE = 'Transcript';

    const ICON = 'id';

    /**
     * @param string $class
     * @return Transcript
     */
    public static function getInstance(string $class = Transcript::class): Transcript
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false]);

        parent::__construct();
    }
}