<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class Values extends CustomBlock
{
    const NAME = 'values';
    const FILENAME = 'values';
    const TITLE = 'Values';

    const ICON = 'id';

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false])
            ->setAllowedBlocks(['core/paragraph', 'core/heading', 'acf/' . ValuesList::NAME]);

        parent::__construct();
    }

    /**
     * @param string $class
     * @return Values
     */
    public static function getInstance(string $class = Values::class): Values
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }
}