<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class ValuesItem extends CustomBlock
{
    const NAME = 'values-item';
    const FILENAME = 'values-item';
    const TITLE = 'Values Item';

    const ICON = 'id';

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false])
            ->setParent(['acf/' . ValuesList::NAME])
            ->setAllowedBlocks(['core/heading', 'core/paragraph']);

        parent::__construct();
    }

    /**
     * @param string $class
     * @return ValuesItem
     */
    public static function getInstance(string $class = ValuesItem::class): ValuesItem
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }
}