<?php

namespace FINNPartners\Theme\Block\Register;

use WpAdvanceCustomFieldsExtend\AbstractClass\CustomBlock;

class ValuesList extends CustomBlock
{
    const NAME = 'values-list';
    const FILENAME = 'values-list';
    const TITLE = 'Values List';

    const ICON = 'id';

    public function __construct()
    {
        $this->setName(self::NAME)
            ->setTitle(self::TITLE)
            ->setRenderTemplate(self::FILENAME . '.php')
            ->setKeywords(['FP'])
            ->setIcon(self::ICON)
            ->setSupports(['jsx' => true, 'align' => false])
            ->setAllowedBlocks(['acf/' . ValuesItem::NAME]);

        parent::__construct();
    }

    /**
     * @param string $class
     * @return ValuesList
     */
    public static function getInstance(string $class = ValuesList::class): ValuesList
    {
        return parent::getInstance($class); // TODO: Change the autogenerated stub
    }
}